feat: Convert benchmark.sh to python and add unit tests
intel-retail/performance-tools pull request #34
Opened 2024-03-21 19:39 UTC by ejlee3

## PR Checklist

- [x] Added label to the Pull Request for easier discoverability and search
- [x] Commit Message meets guidelines as indicated in the URL https://github.com/intel-retail/performance-tools/blob/main/CONTRIBUTING.md
- [x] Every commit is a single defect fix and does not mix feature addition or changes
- [ ] Unit Tests have been added for new changes
- [ ] Updated Documentation as relevant to the changes
- [ ] All commented code has been removed
- [ ] If you've added a dependency, you've ensured license is compatible with repository license and clearly outlined the added dependency.
- [ ] PR change contains code related to security
- [ ] PR introduces changes that breaks compatibility with other modules (If YES, please provide details below)

## What are you changing?

## Issue this PR will close

close: #**issue_number**

## Anything the reviewer should know when reviewing this PR?

## Test Instructions if applicable

Prerequisites:
- python environment with Python 3.12.2 (can use [miniconda](https://rsd-intel.slack.com/archives/C02E1TXQS8Z/p1711055235807679?thread_ts=1711050322.426669&cid=C02E1TXQS8Z) and create a [Python 3.12.2 env](https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-python.html))
- installed necessary packages listed in requirements.txt

1. Pull the latest changes from this branch and from the retail-use-cases for updated compose files
2. change directories to the `benchmark-script` directory
3.  change directories `cd docker` and run `make build-igt` to build the benchmark docker container
4. change directories back `cd ..`
5. Ensure that the benchmarking script works run something like this
    ```
    python benchmark.py --compose_file ../../retail-use-cases/use-cases/gst_capi/add_camera-simulator.yml --compose_file ../../retail-use-cases/use-cases/gst_capi/add_gst_capi_yolov5_ensemble.yml
    ```
    **Note**: it is possible to provide other input variables - use `python benchmark.py --help` to see all available args
6.  run the unit tests in benchmark_test.py
    ```
    python -m unittest -v benchmark_test.py
    ```

## If the there are associated PRs in other repositories, please link them here (i.e. intel-retail/performance-tools )

2024-03-26 21:26 UTC, jim-wang-intel commented on benchmark-scripts/benchmark.py
> +        p = subprocess.Popen(compose_args, stdout=subprocess.PIPE,
add # nosec to ignore for now

2024-03-26 21:26 UTC, jim-wang-intel commented on benchmark-scripts/benchmark_test.py
> +import subprocess
add # nosec ignore for now

2024-03-26 21:31 UTC, jim-wang-intel commented on benchmark-scripts/benchmark_test.py
let's add a make file target for running unit tests and get the code coverage please

2024-03-26 22:31 UTC, brian-intel commented on benchmark-scripts/benchmark.py
> +    compose_files.append(os.path.abspath(os.path.join(
Can you add a comment to specify that this is the benchmark docker-compose file.

2024-03-27 18:43 UTC, jim-wang-intel requested changes
makefile target `python-test` needs to change to include the coverage report data

2024-03-27 18:43 UTC, jim-wang-intel commented on benchmark-scripts/Makefile
> +	python -m unittest benchmark_test.py
python coverage report doesn't work with this together yet, change to include the unit test report into coverage report:

```suggestion
	python -m coverage run -m unittest benchmark_test.py
```

2024-03-27 20:59 UTC, brian-intel requested changes

2024-03-27 20:59 UTC, brian-intel commented on benchmark-scripts/Makefile
>  	docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock -v `pwd`/results:/tmp/results --net=host --privileged benchmark:dev /bin/bash
Add copyright header to Makefile

# Copyright © 2024 Intel Corporation. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

2024-03-27 21:02 UTC, brian-intel commented on benchmark-scripts/camera-simulator.sh
>      if [ -z "$CAMERAS" ]; then
Copyright date

2024-03-27 23:00 UTC, brian-intel approved these changes
LGTM

2024-03-27 23:08 UTC, jim-wang-intel approved these changes
unit tests and coverage work

2024-03-28 15:00 UTC, merged